### ISSUE TITLE
lowerCamelCase for quick suggestions

### ISSUE THREAD

**Issue by john-cj** [stef-levesque/vscode-autohotkey#12]
First of all, thank you for this extension - very useful. Personally, I use it together with Code Runner, which allows me to run AutoHotkey scripts with Alt-Ctrl-N.

However, there is one very annoying thing - UpperCamelCase which is used for quick suggestions:

![camelcase](https://user-images.githubusercontent.com/18004961/38196018-48abf72e-3689-11e8-9de5-3ae95c2882e8.png)

From my point of view, it will be very useful for a lot of users to have an option to use lowerCamelCase instead.

The main reason to change UpperLowerCase to lowerCamelCase is that it's much easier to type when you write the code outside powerful editor - i.e. your code will be consistent across VS Code and Notepad.

Probably, there is no need to change default behaviour - instead, lowerCamelCase should be implemented as an additional option,

Any plans to change it?

**Comment by denolfe** [comment]
Pascal-case is the convention used in all of the AutoHotkey documentation and the majority of code examples elsewhere. I fail to see how using camel-case instead of pascal would be an improvement in the way of enforcing code consistency.

From a practicality standpoint, it is very difficult to support both casings in VS Code because all of the snippets are defined in `snippets/ahk.json`. Adding camel-casing would mean seeing double of each of the suggestions. In the short-term, you can go through and change your `ahk.json` to have the casing you desire.

**Comment by john-cj** [comment]
@denolfe Yeah, I will change my "ahk.json". Thanks!

**Comment by stef-levesque** [comment]
Closing for now, based on feedback.
